### ISSUE TITLE
SRTService에 로그인 함수가 없어서 발생하는 현상

### ISSUE THREAD

**Issue by e7217** [e7217/srt-rsrv#18]
```bash
Traceback (most recent call last):
  File "C:\Users\e7217\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\e7217\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\projects\srt-rsrv\main.py", line 19, in run_reserve
    app.run()
  File "D:\projects\srt-rsrv\main.py", line 13, in run
    self.reserve_service.login()
  File "D:\projects\srt-rsrv\services\reserve.py", line 18, in login
    return self.train_service.login()
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SRTService' object has no attribute 'login'
```

**Comment by e7217** [comment]
위 이슈 해결 후, 다음 에러 발생.
```bash
Traceback (most recent call last):
  File "C:\Users\e7217\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\e7217\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "d:\projects\srt-rsrv\main.py", line 19, in run_reserve
    app.run()
  File "d:\projects\srt-rsrv\main.py", line 14, in run
    self.reserve_service.reserve_loop()
  File "d:\projects\srt-rsrv\services\reserve.py", line 26, in reserve_loop
    if self.reserve():
       ^^^^^^^^^^^^^^
  File "d:\projects\srt-rsrv\services\reserve.py", line 21, in reserve
    return self.train_service.reserve(self.ticket)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\projects\srt-rsrv\services\srt_service.py", line 34, in reserve
    self.reservation = self.srt.reserve(train, _ticket["passengers"])
                                               ~~~~~~~^^^^^^^^^^^^^^
TypeError: 'Ticket' object is not subscriptable
```
